runtime: nodejs22
instance_class: F1

automatic_scaling:
  min_instances: 1
  max_instances: 3

env_variables:
  NODE_ENV: 'production'
  DATA_DIR: '/tmp/session_auth'

handlers:
  - url: /.*
    script: auto
    secure: always
